# Setup
title:               nu1lptr
tagline:             'A blog.'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://nullptr.page
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              nu1lptr
  url:               https://twitter.com/nu1lptr
  email:             github@nullptr.page

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id:
